name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpstan analyse

  tests:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - run: vendor/bin/phpunit
